version: '3.9'
volumes:
  base_feedback_2025:
    external: true

services:
  db:
    image: phdcoder/postgresbr
    restart: always
    volumes:
      - base_feedback_2025:/var/lib/postgresql/data/pgdata
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: $APP_USER
      POSTGRES_DB: $APP_DB
      POSTGRES_PASSWORD: $APP_PASS
      PGDATA: /var/lib/postgresql/data/pgdata
      LANG: pt_BR.utf8
    ports:
      - "5439:5432"
  nginx:
    image: local/nginx-python
    build:
      context: ./nginx
    ports:
      - "1080:80"
  app:
    depends_on:
      - nginx
      - db
    image: local/app-python
    build: .
    volumes:
      - ./app:/app
    working_dir: /app
    environment:
      DB_USER: $APP_USER
      DB_DATABSE: $APP_DB
      DB_PASSWORD: $APP_PASS
